# Generated by Django 5.1.4 on 2026-04-28 20:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Plantilla de agenda",
                "verbose_name_plural": "Plantillas de agenda",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MiembroConsistorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("cargo", models.CharField(max_length=120)),
                (
                    "tipo_miembro",
                    models.CharField(
                        choices=[
                            ("anciano", "Anciano"),
                            ("diacono", "Diácono"),
                            ("pastor", "Pastor"),
                            ("invitado", "Invitado"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Miembro de consistorio",
                "verbose_name_plural": "Miembros de consistorio",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="TipoSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de sesión",
                "verbose_name_plural": "Tipos de sesión",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="BitacoraSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("referencia", models.CharField(max_length=120)),
                ("accion", models.CharField(max_length=120)),
                ("detalle", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bitacora_actas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora de sesión",
                "verbose_name_plural": "Bitácoras de sesión",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="AsuntoPendiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=220)),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_proceso", "En proceso"),
                            ("pospuesto", "Pospuesto"),
                            ("resuelto", "Resuelto"),
                        ],
                        default="abierto",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("fecha_ingreso", models.DateField(default=django.utils.timezone.now)),
                ("activo", models.BooleanField(default=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pendientes",
                        to="actas_app.miembroconsistorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asunto pendiente",
                "verbose_name_plural": "Asuntos pendientes",
                "ordering": ["estado", "-fecha_ingreso"],
            },
        ),
        migrations.CreateModel(
            name="PuntoAgendaPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("seccion", models.CharField(max_length=80)),
                ("numeral", models.CharField(max_length=20)),
                ("titulo", models.CharField(max_length=220)),
                (
                    "tipo_punto",
                    models.CharField(
                        choices=[
                            ("apertura", "Apertura"),
                            ("agenda", "Discusión agenda"),
                            ("acta_anterior", "Acta anterior"),
                            ("informe", "Informe"),
                            ("correspondencia", "Correspondencia"),
                            ("pendiente", "Asunto pendiente"),
                            ("nuevo", "Asunto nuevo"),
                            ("cierre", "Cierre"),
                        ],
                        default="nuevo",
                        max_length=30,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos",
                        to="actas_app.agendaplantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punto de agenda de plantilla",
                "verbose_name_plural": "Puntos de agenda de plantilla",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SesionConsistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField()),
                ("anio", models.PositiveIntegerField(default=2026)),
                ("fecha", models.DateField()),
                ("lugar", models.CharField(max_length=255)),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("quorum_requerido", models.PositiveIntegerField(default=1)),
                ("quorum_alcanzado", models.PositiveIntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_desarrollo", "En desarrollo"),
                            ("en_revision", "En revisión"),
                            ("aprobada", "Aprobada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("observaciones_generales", models.TextField(blank=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                (
                    "aprobada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_moderadas",
                        to="actas_app.miembroconsistorio",
                    ),
                ),
                (
                    "revisada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_secretariadas",
                        to="actas_app.miembroconsistorio",
                    ),
                ),
                (
                    "tipo_sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones",
                        to="actas_app.tiposesion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión consistorial",
                "verbose_name_plural": "Sesiones consistoriales",
                "ordering": ["-anio", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="SeguimientoAsuntoPendiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("detalle", models.TextField()),
                (
                    "estado_anterior",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_proceso", "En proceso"),
                            ("pospuesto", "Pospuesto"),
                            ("resuelto", "Resuelto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_proceso", "En proceso"),
                            ("pospuesto", "Pospuesto"),
                            ("resuelto", "Resuelto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "asunto_pendiente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="actas_app.asuntopendiente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos_pendientes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguimientos",
                        to="actas_app.sesionconsistorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de asunto pendiente",
                "verbose_name_plural": "Seguimientos de asuntos pendientes",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PuntoAgendaSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("seccion", models.CharField(max_length=80)),
                ("numeral", models.CharField(max_length=20)),
                ("titulo", models.CharField(max_length=220)),
                (
                    "tipo_punto",
                    models.CharField(
                        choices=[
                            ("apertura", "Apertura"),
                            ("agenda", "Discusión agenda"),
                            ("acta_anterior", "Acta anterior"),
                            ("informe", "Informe"),
                            ("correspondencia", "Correspondencia"),
                            ("pendiente", "Asunto pendiente"),
                            ("nuevo", "Asunto nuevo"),
                            ("cierre", "Cierre"),
                        ],
                        default="nuevo",
                        max_length=30,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                ("contenido_resumen", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos_agenda",
                        to="actas_app.sesionconsistorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punto de agenda de sesión",
                "verbose_name_plural": "Puntos de agenda de sesión",
                "ordering": ["orden", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InformeSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("area", models.CharField(max_length=120)),
                (
                    "tipo_informe",
                    models.CharField(
                        choices=[
                            ("narrativo", "Narrativo"),
                            ("financiero", "Financiero"),
                        ],
                        default="narrativo",
                        max_length=15,
                    ),
                ),
                ("expositor", models.CharField(max_length=120)),
                ("resumen", models.TextField()),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "ingresos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "egresos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "saldo_final",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "fondo_especial",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes",
                        to="actas_app.sesionconsistorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe de sesión",
                "verbose_name_plural": "Informes de sesión",
                "ordering": ["area"],
            },
        ),
        migrations.CreateModel(
            name="CorrespondenciaSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("remitente", models.CharField(max_length=160)),
                ("asunto", models.CharField(max_length=220)),
                ("descripcion", models.TextField()),
                ("decision", models.TextField(blank=True)),
                ("genera_acuerdo", models.BooleanField(default=False)),
                ("genera_pendiente", models.BooleanField(default=False)),
                (
                    "adjunto",
                    models.FileField(
                        blank=True, null=True, upload_to="actas/correspondencia"
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondencias",
                        to="actas_app.sesionconsistorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correspondencia de sesión",
                "verbose_name_plural": "Correspondencia de sesión",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddField(
            model_name="asuntopendiente",
            name="sesiones",
            field=models.ManyToManyField(
                blank=True,
                related_name="pendientes_vinculados",
                to="actas_app.sesionconsistorial",
            ),
        ),
        migrations.CreateModel(
            name="AsuntoNuevoSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=220)),
                ("descripcion", models.TextField()),
                ("presentado_por", models.CharField(max_length=120)),
                ("decision", models.TextField(blank=True)),
                ("pasa_a_pendiente", models.BooleanField(default=False)),
                ("genera_acuerdo", models.BooleanField(default=False)),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asuntos_nuevos",
                        to="actas_app.sesionconsistorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asunto nuevo",
                "verbose_name_plural": "Asuntos nuevos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="AsistenciaSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "asistencia",
                    models.CharField(
                        choices=[
                            ("presente", "Presente"),
                            ("ausente", "Ausente"),
                            ("excusado", "Excusado"),
                        ],
                        default="ausente",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                (
                    "miembro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="actas_app.miembroconsistorio",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="actas_app.sesionconsistorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia de sesión",
                "verbose_name_plural": "Asistencias de sesión",
                "ordering": ["miembro__apellidos"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sesion", "miembro"),
                        name="uniq_asistencia_sesion_miembro",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AcuerdoConsistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField()),
                ("anio", models.PositiveIntegerField(default=2026)),
                (
                    "origen_tipo",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("correspondencia", "Correspondencia"),
                            ("asunto_nuevo", "Asunto nuevo"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_proceso", "En proceso"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="abierto",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acuerdos",
                        to="actas_app.miembroconsistorio",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acuerdos",
                        to="actas_app.sesionconsistorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acuerdo consistorial",
                "verbose_name_plural": "Acuerdos consistoriales",
                "ordering": ["-anio", "-numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("numero", "anio"), name="uniq_acuerdo_numero_anio"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActaSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("numero_acta", models.PositiveIntegerField()),
                ("anio", models.PositiveIntegerField(default=2026)),
                ("contenido_borrador", models.TextField(blank=True)),
                ("contenido_final", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En revisión"),
                            ("aprobada", "Aprobada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("fecha_redaccion", models.DateTimeField(auto_now_add=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actas_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "redactado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actas_redactadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actas_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sesion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acta",
                        to="actas_app.sesionconsistorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta de sesión",
                "verbose_name_plural": "Actas de sesión",
                "ordering": ["-anio", "-numero_acta"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("numero_acta", "anio"), name="uniq_acta_numero_anio"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sesionconsistorial",
            constraint=models.UniqueConstraint(
                fields=("numero", "anio"), name="uniq_sesion_numero_anio"
            ),
        ),
    ]
