# Generated by Django 5.1.4 on 2026-04-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actas_app", "0002_seed_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaInformeCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Área de informe",
                "verbose_name_plural": "Áreas de informe",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TextoBaseActa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("contenido", models.TextField()),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Texto base de acta",
                "verbose_name_plural": "Textos base de acta",
                "ordering": ["nombre"],
            },
        ),
    ]
